stages:
  - build
  - test

image: lsfiege/laravel-dusk-ci:latest

# Variables
variables:
  MYSQL_ROOT_PASSWORD: root
  MYSQL_USER: homestead
  MYSQL_PASSWORD: secret
  MYSQL_DATABASE: homestead
  DB_HOST: mariadb
  DB_CONNECTION: mysql

composer:
  stage: build
  script:
    - cp .env.gitlab .env
    - cp phpunit.xml.gitlab phpunit.xml
    - composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
  cache:
    key: ${CI_COMMIT_REF_SLUG}-composer
    paths:
      - vendor
  artifacts:
    expire_in: 7 days
    paths:
      - vendor/
      - .env
      - phpunit.xml

phpunit:
  stage: test
  dependencies:
    - composer
  services:
    - mariadb:10.2.15
  script:
    - configure-laravel
    - start-nginx-ci-project
    - ./vendor/bin/phpunit -v --stderr --colors --stop-on-failure
  artifacts:
    paths:
      - ./storage/logs # for debugging
      - ./tests/Browser/screenshots
      - ./tests/Browser/console
    expire_in: 7 days
    when: always

dusk:
  stage: test
  dependencies:
  - composer
  services:
  - mariadb:10.2.15
  script:
  - configure-laravel
  - start-nginx-ci-project
  - nohup ./vendor/laravel/dusk/bin/chromedriver-linux 2>&1 &
  - php artisan dusk --colors --stop-on-failure
  artifacts:
    paths:
    - ./storage/logs # for debugging
    - ./tests/Browser/screenshots
    - ./tests/Browser/console
    expire_in: 7 days
    when: always
